export const NEXT_MONTH = "NEXT_MONTH";
export const PREVIOUS_MONTH = "PREVIOUS_MONTH";
export const NEXT_YEAR_FOR_SELECTION = "NEXT_YEAR_FOR_SELECTION";
export const PREVIOUS_YEAR_FOR_SELECTION = "PREVIOUS_YEAR_FOR_SELECTION";
export const SET_YEAR_SELECTED = "SET_YEAR_SELECTED";
export const SET_MONTH_SELECTED = "SET_MONTH_SELECTED";
export const GET_CONFIRMATON_OF_SELECTED_DAY =
  "GET_CONFIRMATON_OF_SELECTED_DAY";
export const RESET_SELECTION = "RESET_SELECTION";
