export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const SET_EDDITING_STATUS = "SET_EDDITING_STATUS";
export const RESET_EDITTING = "RESET_EDITTING";
